### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by stefanseefeld** [plone/Installers-UnifiedInstaller#45] opened 2015-10-15 19:02 UTC
I'm trying to run the 'unified installer'. Running './install.sh' from Plone-5.0-UnifiedInstaller asks about the desired location (I specify '/usr/local/Plone'), then aborts with:

  ERROR: The executable /usr/local/Plone/zinstance/bin/python2.7 is not functioning
  ERROR: It thinks sys.prefix is u'/usr' (should be u'/usr/local/Plone/zinstance')
  ERROR: virtualenv is not compatible with this system or executable

**Comment by smcmahon** [comment] 2015-10-15 23:34
Was this on debian/ubuntu? They have a bizarre patch for Python-2.7 that prevents creation of virtual environments under /usr/local when recent versions of setuptools are used. That's why the default target for "root" installs switched to /opt/plone in 5.0.

**Comment by stefanseefeld** [comment] 2015-10-15 23:38
This is on Fedora. (I don't know where that /usr/local/Plone/zinstance/bin/python executable is coming from, and how it computes the value of sys.prefix, but it does indeed report /usr, which is obviously wrong.)

**Comment by smcmahon** [comment] 2015-10-15 23:49
Perhaps they're using a similar patch. Can you try an install to a location that's not under /usr/local? If it works, that would really pin this down.

**Comment by stefanseefeld** [comment] 2015-10-16 04:47
I tried with the default install prefix ($HOME/Plone), resulting in the same error.

**Comment by smcmahon** [comment] 2015-10-16 16:12
OK, what's your Fedora version?

**Comment by stefanseefeld** [comment] 2015-10-16 16:23
The latest, Fedora 22.
But, looking into this a little more in depth, I realize the problem may be unrelated to this: My default environment uses a non-system Python (installed from anaconda.org). When I change my PATH so the system Python is found first, the Plone installation appears to be working correctly.
It sounds like what you are saying is that this is a Python bug. Is that correct ? Is there a test I can perform on the Python installation to demonstrate the (apparently erroneous) behavior, and even report it upstream if that's indeed a Python bug ?

**Comment by smcmahon** [comment] 2015-10-16 16:34
See if you can use a current virtualenv to create a virtual environment in your target directory with the non-system Python. If it fails, you've got a great bug demonstration method.

I'm closing this since it seems likely the problem isn't in code we control. If that turns out not to be the case, please re-open.

**Closed by smcmahon** 2015-10-16 16:34 UTC
